const list = [
    {
      id: 1,
      title: "BLIVE",
      detail: "BLIVE Men's Regular Fit Round Neck Printed T-Shirt | Printed T-Shirt",
      price: 244,
      img: "https://m.media-amazon.com/images/I/51xeCPdiHiL._SX522._SX._UX._SY._UY_.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "Dennis Lingo",
      detail: "Dennis Lingo Men’s Casual Slim Fit Polo Neck T-Shirt, Half Sleeves Vertical Striped Pure Cotton T-Shirt for Men",
      price: 98,
      img: "https://m.media-amazon.com/images/I/51VhIblJzhL._UY550_.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "Amazon",
      detail: "Amazon Brand - Symbol Men's Regular Polo Shirt",
      price: 143,
      img: "https://m.media-amazon.com/images/I/81F+zV1Y32L._UX466_.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "Alan Jones",
      detail: "Alan Jones Clothing Men's Slim Fit Polo T-Shirt",
      price: 57,
      img: "https://m.media-amazon.com/images/I/613iJ3q07bL._UY550_.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "My First 1000 Words",
      detail: "by Wonder House Books  | 1 January 2018",
      price: 149,
      img: "https://m.media-amazon.com/images/I/51xeCPdiHiL._SX522._SX._UX._SY._UY_.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "U.S. POLO",
      detail: "U.S. POLO ASSN. Men's Striped Regular fit T-Shirt",
      price: 135,
      img: "https://m.media-amazon.com/images/I/81UafevpWoL._UY550_.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Pre-School Activities Pack ",
      detail: "by Om Books Editorial Team  | 1 January 2021",
      price: 693,
      img: "https://m.media-amazon.com/images/I/51xeCPdiHiL._SX522._SX._UX._SY._UY_.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Maniac Boy",
      detail: "Maniac Boy's Slim Fit T-shirt",
      price: 289,
      img: "https://m.media-amazon.com/images/I/51YDLAyFZlS._UY550_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "Polo",
      detail: "Allen Solly Men's Polo",
      price: 80,
      img: "https://m.media-amazon.com/images/I/91TndAyYh0L._UY550_.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "RodZen Men's",
      detail: "RodZen Men's Cotton Half Sleeve Regular Fit Striped T-Shirt",
      price: 86,
      img: "https://m.media-amazon.com/images/I/619SqQW1NYL._UY550_.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Scott",
      detail: "Scott International Men's Regular Fit T-Shirt (Pack of 3)",
      price: 120,
      img: "https://m.media-amazon.com/images/I/71vp8Lec9JL._UX466_.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "SHAUN",
      detail: "SHAUN Men T-Shirt (N704MT3_$P_Pack of 3)",
      price: 157,
      img: "https://m.media-amazon.com/images/I/813gJRfNKKL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },
  ];
  
  export default list;